fun main() {
//    val manager= ResourseManager()
//    val minerals= OutpostResource(1, "Minerals", 300)
//    val gas = OutpostResource(2, "Gas", 100)
//    manager.add(minerals)
//    manager.add(gas)
//    manager.printAll()
//
//    val bonus =minerals.copy(amount = minerals.amount + 50)
//    println("Копия минералов с бонусом: $bonus")
    val manager = ResourseManager()
    manager.add(OutpostResource(1, "Minerals", 120))
    manager.add(OutpostResource(2, "Gas", 40))
    val generator = EnergyGeneretor()
    val lab= ResearchLab()
    generator.performAction(manager)
    lab.performAction(manager)
    println()
    manager.printAll()
}